# Generated by Django 5.0.1 on 2024-05-12 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_key', models.CharField(max_length=255)),
                ('remote_addr', models.CharField(blank=True, max_length=255)),
                ('ua_string', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.CharField(blank=True, default='', max_length=255)),
                ('os', models.CharField(blank=True, default='', max_length=200)),
                ('hash', models.CharField(help_text='"MD5 hash generated from request properties', max_length=32, unique=True)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
