# Generated by Django 5.0.1 on 2024-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='hash',
            field=models.CharField(help_text='"MD5 hash generated from request properties', max_length=32),
        ),
    ]
