# Generated by Django 5.0.1 on 2024-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_visit', '0005_alter_uservisit_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='http_method',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
