# Generated by Django 5.0.1 on 2024-05-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_visit', '0006_uservisit_http_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisit',
            name='hash',
            field=models.CharField(help_text='"MD5 hash generated from request properties', max_length=255, unique=True),
        ),
    ]
