# Generated by Django 5.0.1 on 2024-02-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_reviews_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')]),
        ),
        migrations.DeleteModel(
            name='RatingStars',
        ),
    ]
