# Generated by Django 5.0.1 on 2024-02-15 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_rating_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Значения рейтинга',
                'verbose_name_plural': 'Значение рейтинга',
            },
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie.ratingstars', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
