# Generated by Django 5.0.1 on 2024-02-15 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie.ratingstars', verbose_name='Рейтинг'),
        ),
    ]
