# Generated by Django 5.0.1 on 2024-02-28 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Создал', 'Создал'), ('Изменил', 'Изменил'), ('Удалил', 'Удалил')], max_length=50, null=True, verbose_name='Действие')),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Имя модели')),
                ('record_id', models.IntegerField(null=True, verbose_name='ID записи')),
                ('data_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('data', models.JSONField(default=dict, null=True, verbose_name='Измененные данные')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
                'ordering': ['data_create'],
            },
        ),
    ]
