# Generated by Django 5.0.1 on 2024-05-11 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(blank=True, choices=[('Создал', 'Создал'), ('Изменил', 'Изменил'), ('Удалил', 'Удалил')], max_length=50, null=True, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Измененные данные'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя модели'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='record_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID записи'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
